/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallaprinc;

import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class fromVivienda extends javax.swing.JFrame {
       int posi;
       
      
    public fromVivienda() {
        initComponents();
        this.setLocationRelativeTo(null);
        Actualizar();
       
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDescrip = new javax.swing.JTextField();
        txtDirec = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MConstru = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        MLote = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        DGarantia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CantHabi = new javax.swing.JTextField();
        CantBanos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        PrecioBase = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TContruc = new javax.swing.JComboBox<>();
        Caterra = new javax.swing.JComboBox<>();
        txtEstado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Insertar = new javax.swing.JButton();
        EliminarTodo = new javax.swing.JButton();
        Seleccionar = new javax.swing.JButton();
        BnBuscar = new javax.swing.JButton();
        Mostrar = new javax.swing.JButton();
        Cochera = new javax.swing.JComboBox<>();
        Propieta = new javax.swing.JTextField();
        GuardarModificacion = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        VolvermenuPrincipal = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel2.setText("ID ");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });

        jLabel3.setText("Descripción");

        txtDescrip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripKeyTyped(evt);
            }
        });

        txtDirec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirecActionPerformed(evt);
            }
        });
        txtDirec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDirecKeyTyped(evt);
            }
        });

        jLabel4.setText("Direccion ");

        jLabel5.setText("M.Construcción");

        MConstru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MConstruKeyTyped(evt);
            }
        });

        jLabel6.setText("M.Lote");

        MLote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MLoteKeyTyped(evt);
            }
        });

        jLabel7.setText("Cochera");

        DGarantia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DGarantiaKeyTyped(evt);
            }
        });

        jLabel8.setText("Deposito de garantia");

        jLabel9.setText("Cantidad de Habitaciones");

        CantHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantHabiActionPerformed(evt);
            }
        });
        CantHabi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CantHabiKeyTyped(evt);
            }
        });

        CantBanos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CantBanosKeyTyped(evt);
            }
        });

        jLabel10.setText("Cantidad de baños");

        jLabel11.setText("Carretera");

        jLabel12.setText("Precio Base");

        PrecioBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioBaseActionPerformed(evt);
            }
        });
        PrecioBase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PrecioBaseKeyTyped(evt);
            }
        });

        jLabel13.setText("Estado");

        jLabel14.setText("Propetario");

        jLabel15.setText("Tipo de Contrucción");

        TContruc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir", "Block", "Baldosa", "Super", "madera", "mixta" }));
        TContruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TContrucKeyTyped(evt);
            }
        });

        Caterra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir", "Lastre", "Pavimentada", "adoquinada" }));
        Caterra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CaterraKeyTyped(evt);
            }
        });

        txtEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir", "Disponible", "Alquilado", "Inactiva" }));

        Tabla.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Descripción", "Dirrección", "M.Contruc", "M.Lote", "T.Construc", "Cochera", "C. Habitac", "C. baños", "Carretera", "Precio Base", "Deposito.G", "Propetario", "Estado"
            }
        ));
        Tabla.setRowHeight(18);
        jScrollPane1.setViewportView(Tabla);

        Insertar.setText("Insertar");
        Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarActionPerformed(evt);
            }
        });

        EliminarTodo.setText("Eliminar Todo");
        EliminarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarTodoActionPerformed(evt);
            }
        });

        Seleccionar.setText("Seleccionar");
        Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarActionPerformed(evt);
            }
        });

        BnBuscar.setText("Buscar");
        BnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnBuscarActionPerformed(evt);
            }
        });

        Mostrar.setText("Mostrar");
        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });

        Cochera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir", "SI", "NO" }));
        Cochera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CocheraKeyTyped(evt);
            }
        });

        Propieta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PropietaKeyTyped(evt);
            }
        });

        GuardarModificacion.setText("Guardar Modificación");
        GuardarModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarModificacionActionPerformed(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        VolvermenuPrincipal.setText("Volver a menu Principal");
        VolvermenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolvermenuPrincipalActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(Insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EliminarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GuardarModificacion)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel2))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(24, 24, 24)
                                                    .addComponent(txtDirec, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(MConstru, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                                            .addComponent(MLote)))
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Cochera, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addGap(18, 18, 18)
                                            .addComponent(TContruc, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel10)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(jLabel9)))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Caterra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(DGarantia, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                                .addComponent(PrecioBase)
                                                .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Propieta))
                                            .addComponent(CantBanos, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CantHabi, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(VolvermenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(BnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(37, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDirec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(MConstru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(MLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TContruc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cochera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CantHabi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VolvermenuPrincipal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(CantBanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(Caterra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(PrecioBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(Propieta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Insertar)
                    .addComponent(EliminarTodo)
                    .addComponent(Seleccionar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuardarModificacion)
                    .addComponent(BnBuscar)
                    .addComponent(Eliminar)
                    .addComponent(Mostrar))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CantHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantHabiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantHabiActionPerformed

    private void PrecioBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioBaseActionPerformed

    private void txtDirecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirecActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
        Actualizar();
        Limpiar();

    }//GEN-LAST:event_MostrarActionPerformed

    private void InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarActionPerformed
       
          ///Este "if" realiza una revisión que todo los textfields esten llenos
        if(   !CantBanos.getText().equals("")   &&  !CantHabi.getText().equals("")   &&
             !DGarantia.getText().equals("")   &&  !MConstru.getText().equals("")   &&
             !MLote.getText().equals("")       &&  !PrecioBase.getText().equals("") &&
             !Propieta.getText().equals("")    &&  !txtDescrip.getText().equals("") &&
             !txtDirec.getText().equals("")    &&  !txtID.getText().equals("")   ){     
         
           
        //// Este "for" realiza una busqueda para  comprobar si el identicador ingresado Existe 
                 Boolean Existencia1=true;
                 String str = txtID.getText();
                 for (int i = 0; i < MenuPrinc.listaVivienda.size(); i++) {
                      Viviendas Aux =  (Viviendas) MenuPrinc.listaVivienda.get(i);
                     if(Integer.toString(Aux.getIdviviendas()).equals(str)){
                           Existencia1=false;
                      }    
                  }
         
                if(Existencia1){
                
                   ///Enviando datos al contructor
                   Viviendas  NuevaVivienda = new Viviendas(Integer.parseInt(txtID.getText()),txtDescrip.getText(),
                   txtDirec.getText(),Integer.parseInt(MConstru.getText()),Integer.parseInt(MLote.getText()),
                   (String) TContruc.getSelectedItem(),true,Integer.parseInt(CantHabi.getText()),
                    Integer.parseInt(CantBanos.getText()), (String) Caterra.getSelectedItem(),
                    Integer.parseInt(PrecioBase.getText()),Integer.parseInt(DGarantia.getText()),
                    Propieta.getText(),(String)txtEstado.getSelectedItem());
                    MenuPrinc.listaVivienda.add(NuevaVivienda);
  
                        Actualizar();  //Muestra el Contenido en JTable
                        Limpiar(); //Limpia los Jtable 
                 }else{
                   JOptionPane.showMessageDialog(null,"El Identificador :"+txtID.getText()+" Ya  existe , Por favor ingrese un nuevo valor");
                 }
                 
                 
                 
         }else{
              JOptionPane.showMessageDialog(null,"Hay Una casilla vacia");
                     
         }
    
    }//GEN-LAST:event_InsertarActionPerformed
     
   
    
    public void Limpiar(){
        
     CantBanos.setText("");
     CantHabi.setText("");
     Caterra.setSelectedIndex(0);
     Cochera.setSelectedIndex(0);
     DGarantia.setText("");
     MConstru.setText("");
     MLote.setText("");
     PrecioBase.setText("");
     Propieta.setText("");
     TContruc.setSelectedIndex(0);
     txtDescrip.setText("");
     txtDirec.setText("");
     txtEstado.setSelectedIndex(0);
     txtID.setText("");
             
    }
    
    
    public void Actualizar(){
         
         
            String M[][] = new String[MenuPrinc.listaVivienda.size()][14];
            
            for (int i = 0; i < MenuPrinc.listaVivienda.size(); i++) {
             Viviendas Aux =  (Viviendas) MenuPrinc.listaVivienda.get(i);
             
             M[i][0]= Integer.toString(Aux.getIdviviendas());
             M[i][1]=Aux.getDescripcion();
             M[i][2]=Aux.getDireccion();
             M[i][3]=Integer.toString(Aux.getMtsConstrucc());
             M[i][4]=Integer.toString(Aux.getMtsLote());
             M[i][5]=Aux.getTipoConstruccion();
             M[i][6]=Aux.getCochera().toString();
             M[i][7]=Integer.toString(Aux.getCantHabitacion());
             M[i][8]=Integer.toString(Aux.getCantbanos());
             M[i][9]=Aux.getCarretera();
             M[i][10]=Integer.toString(Aux.getPrecioBase());
             M[i][11]=Integer.toString(Aux.getDepositoGarantia());
             M[i][12]=Aux.getPropetarios();
             M[i][13]=Aux.getEstado();
                     
            }
           
            
            
            Tabla.setModel(new javax.swing.table.DefaultTableModel(
            M,
            new String [] {
                "ID", "Descripción", "Dirrección", "M.Contruc", "M.Lote", "T.Construc", "Cochera",
                "C. Habitac", "C. baños", "Carretera", "Precio Base", "Deposito.G", "Propetario", "Estado"
            }
        ));
            
           
            //
          
      
     }
    
    
    
    
    
    private void SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarActionPerformed

      posi = Tabla.getSelectedRow();
     Viviendas Aux =  (Viviendas) MenuPrinc.listaVivienda.get(posi);
        try {
     CantBanos.setText(Integer.toString(Aux.getCantbanos()));
     CantHabi.setText(Integer.toString(Aux.getCantHabitacion()));
     Caterra.setSelectedItem(Aux.getCarretera());
     Cochera.setSelectedItem(Aux.getCochera());
     DGarantia.setText(Integer.toString(Aux.getDepositoGarantia()));
     MConstru.setText(Integer.toString(Aux.getMtsConstrucc()));
     MLote.setText(Integer.toString(Aux.getMtsLote()));
     PrecioBase.setText(Integer.toString(Aux.getPrecioBase()));
     Propieta.setText(Aux.getPropetarios());
     TContruc.setSelectedItem(Aux.getTipoConstruccion());
     txtDescrip.setText(Aux.getDescripcion());
     txtDirec.setText(Aux.getDireccion());
     txtEstado.setSelectedItem(Aux.getEstado());
     txtID.setText(Integer.toString(Aux.getIdviviendas()));
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null,"SELECCIONE UNA FILA");
        }

    }//GEN-LAST:event_SeleccionarActionPerformed

    private void BnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnBuscarActionPerformed
         Boolean Existencia = false;
     if(!txtBuscar.getText().isEmpty()){
               Viviendas Aux = null;
              String str = txtBuscar.getText();
          for (int i = 0; i < MenuPrinc.listaVivienda.size(); i++) {
              Aux = (Viviendas) MenuPrinc.listaVivienda.get(i);
              if(Integer.toString(Aux.getIdviviendas()).equals(str)){
                mostrarDatos(Aux); 
                Existencia=true;
           }
            
        }
        
    }else{
        
        JOptionPane.showMessageDialog(null,"La casilla Buscar esta vacia");
    }
   
        
        if(Existencia){
        JOptionPane.showMessageDialog(null,"Busqueda finalizada");
        }else{
         JOptionPane.showMessageDialog(null,"Lo sentimos no se ha encontrado la información en la base de datos :(");    
        }
        
         txtBuscar.setText("");
    }//GEN-LAST:event_BnBuscarActionPerformed

    
     public void mostrarDatos(Viviendas Aux) { ///Muestra la persona en la primera fila del Jtable para Mayor comodida
       String M[][]= new String[1][14];
       
             M[0][0]= Integer.toString(Aux.getIdviviendas());
             M[0][1]=Aux.getDescripcion();
             M[0][2]=Aux.getDireccion();
             M[0][3]=Integer.toString(Aux.getMtsConstrucc());
             M[0][4]=Integer.toString(Aux.getMtsLote());
             M[0][5]=Aux.getTipoConstruccion();
             M[0][6]=Aux.getCochera().toString();
             M[0][7]=Integer.toString(Aux.getCantHabitacion());
             M[0][8]=Integer.toString(Aux.getCantbanos());
             M[0][9]=Aux.getCarretera();
             M[0][10]=Integer.toString(Aux.getPrecioBase());
             M[0][11]=Integer.toString(Aux.getDepositoGarantia());
             M[0][12]=Aux.getPropetarios();
             M[0][13]=Aux.getEstado();
          
             VerPersona(M); // Este metodo muestra los datos buscados, en los textfields
            Tabla.setModel(new javax.swing.table.DefaultTableModel(
            M,
            new String [] {
                "ID", "Descripción", "Dirrección", "M.Contruc", "M.Lote", "T.Construc", "Cochera",
                "C. Habitac", "C. baños", "Carretera", "Precio Base", "Deposito.G", "Propetario", "Estado"
            }
        ));
          
    }
     
     
     public  void VerPersona(String[][] M) {  ///Este metodo muestra los datos en  los textfields
     
     txtID.setText( M[0][0]);
     txtDescrip.setText( M[0][1]);
     txtDirec.setText( M[0][2]);
     MConstru.setText(M[0][3]);
     MLote.setText(M[0][4]);
     TContruc.setSelectedItem(M[0][5]);
     Cochera.setSelectedItem(M[0][6]);
     CantHabi.setText(M[0][7]);
     CantBanos.setText(M[0][8]);
     Caterra.setSelectedItem(M[0][9]);
     PrecioBase.setText(M[0][10]);
     DGarantia.setText(M[0][11]);
     Propieta.setText(M[0][12]);
     txtEstado.setSelectedItem(M[0][13]);
           
           
    }
    private void EliminarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarTodoActionPerformed
       String V [] ={"SI","NO"}; 
       
      int N = JOptionPane.showOptionDialog(null,"¿Deseas Eliminar Esta información?","Titulo",0,0,null,V,null);
      if(N==0){
        MenuPrinc.listaVivienda.removeAll(MenuPrinc.listaVivienda);
        Actualizar();
      }
       

    }//GEN-LAST:event_EliminarTodoActionPerformed

    private void GuardarModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarModificacionActionPerformed
  

     Viviendas ViviendaModificada = new Viviendas(Integer.parseInt(txtID.getText()),txtDescrip.getText(),
                 txtDirec.getText(),Integer.parseInt(MConstru.getText()),Integer.parseInt(MLote.getText()),
                 (String) TContruc.getSelectedItem(),true,Integer.parseInt(CantHabi.getText()),
                 Integer.parseInt(CantBanos.getText()), (String) Caterra.getSelectedItem(),
                 Integer.parseInt(PrecioBase.getText()),Integer.parseInt(DGarantia.getText()),
                 Propieta.getText(),(String)txtEstado.getSelectedItem());
                 
       MenuPrinc.listaVivienda.set(posi,ViviendaModificada );
       Limpiar();
       Actualizar();

       
    }//GEN-LAST:event_GuardarModificacionActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
     int press = evt.getKeyChar();
     if(press==10){
      txtDescrip.requestFocus();
     }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDKeyTyped

    private void txtDescripKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripKeyTyped
     int press = evt.getKeyChar();
     if(press==10){
       txtDirec.requestFocus();
     }


        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripKeyTyped

    private void txtDirecKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDirecKeyTyped
        int press = evt.getKeyChar();
      if(press==10){
       MConstru.requestFocus();
     }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirecKeyTyped

    private void MConstruKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MConstruKeyTyped

       int press = evt.getKeyChar();
      if(press==10){
        MLote.requestFocus();
     }



        // TODO add your handling code here:
    }//GEN-LAST:event_MConstruKeyTyped

    private void MLoteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MLoteKeyTyped
      int press = evt.getKeyChar();
      if(press==10){
        TContruc.requestFocus();
     }



        // TODO add your handling code here:
    }//GEN-LAST:event_MLoteKeyTyped

    private void TContrucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TContrucKeyTyped
       int press = evt.getKeyChar();
      if(press==10){
         Cochera.requestFocus();
     }

       
    }//GEN-LAST:event_TContrucKeyTyped

    private void CocheraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CocheraKeyTyped
        int press = evt.getKeyChar();
      if(press==10){
          CantHabi.requestFocus();
         
     }

    }//GEN-LAST:event_CocheraKeyTyped

    private void CantHabiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantHabiKeyTyped
        int press = evt.getKeyChar();
      if(press==10){
           CantBanos.requestFocus();
     }

        // TODO add your handling code here:
    }//GEN-LAST:event_CantHabiKeyTyped

    private void CantBanosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantBanosKeyTyped
         int press = evt.getKeyChar();
      if(press==10){
          Caterra.requestFocus();
     }




        // TODO add your handling code here:
    }//GEN-LAST:event_CantBanosKeyTyped

    private void CaterraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CaterraKeyTyped

     int press = evt.getKeyChar();
      if(press==10){
          PrecioBase.requestFocus();
           
     }

     
    }//GEN-LAST:event_CaterraKeyTyped

    private void PrecioBaseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrecioBaseKeyTyped
     int press = evt.getKeyChar();
      if(press==10){
            DGarantia.requestFocus();
     }


        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioBaseKeyTyped

    private void DGarantiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DGarantiaKeyTyped
   int press = evt.getKeyChar();
      if(press==10){
           Propieta.requestFocus();
     }



        // TODO add your handling code here:
    }//GEN-LAST:event_DGarantiaKeyTyped

    private void PropietaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PropietaKeyTyped

     int press = evt.getKeyChar();
      if(press==10){
          txtEstado.requestFocus();
     }


        // TODO add your handling code here:
    }//GEN-LAST:event_PropietaKeyTyped

    private void VolvermenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolvermenuPrincipalActionPerformed
     
         MenuPrinc Volv = new  MenuPrinc();
         Volv.setVisible(true);
    }//GEN-LAST:event_VolvermenuPrincipalActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
       int Fila = Tabla.getSelectedRow();
       if(Fila>=0){
          MenuPrinc.listaVivienda.remove(Fila);
          Actualizar();
       }else{
           
           JOptionPane.showMessageDialog(null,"Seleccione La fila que desea eliminar");
       }



        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fromVivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fromVivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fromVivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fromVivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fromVivienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BnBuscar;
    private javax.swing.JTextField CantBanos;
    private javax.swing.JTextField CantHabi;
    private javax.swing.JComboBox<String> Caterra;
    private javax.swing.JComboBox<String> Cochera;
    private javax.swing.JTextField DGarantia;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton EliminarTodo;
    private javax.swing.JButton GuardarModificacion;
    private javax.swing.JButton Insertar;
    private javax.swing.JTextField MConstru;
    private javax.swing.JTextField MLote;
    private javax.swing.JButton Mostrar;
    private javax.swing.JTextField PrecioBase;
    private javax.swing.JTextField Propieta;
    private javax.swing.JButton Seleccionar;
    private javax.swing.JComboBox<String> TContruc;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton VolvermenuPrincipal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDescrip;
    private javax.swing.JTextField txtDirec;
    private javax.swing.JComboBox<String> txtEstado;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables

 

   
}
