/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallaprinc;

import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class fromAlquileres extends javax.swing.JFrame {
     int posi;
    /**
     * Creates new form fromAlquileres
     */
    public fromAlquileres() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtNumAlquiler = new javax.swing.JTextField();
        FechaCont = new javax.swing.JTextField();
        txtNumAdult = new javax.swing.JTextField();
        txtNumNinos = new javax.swing.JTextField();
        CantMeses = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDepositoG = new javax.swing.JTextField();
        txtPrecioAlquiler = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPorcenIA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCedInquilino = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIDVivi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setText("Numero de alquiler");

        jLabel2.setText("Fecha de Contrato");

        jLabel3.setText("Cantidad de meses");

        jLabel4.setText("Numero de Adultos");

        jLabel5.setText("Numero de niños");

        jLabel6.setText("Deposito de Garantia");

        jLabel7.setText("Precio de Alquiler");

        jLabel8.setText("Porcentaje incremento.Alquiler");

        jLabel9.setText("Cedula del Inquilino");

        jLabel10.setText("ID vivienda");

        jButton1.setText("Insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar Todo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Seleccionar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Guardar Modificación");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Buscar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setText("Mostrar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel11.setText("Estado");

        txtEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir", "Vigente", "Vencido", "Cancelado", " " }));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero.Alquiler", "Fecha.contrato", "Cant.Meses", "Numero.Adultos", "Numero.niños", "Deposito.G", "Precio.Alquiler", "Porce.I.A", "Cedula.Inquilino", "ID.Vivienda", "Estado"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton7.setText("Volver a Menu principal");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FechaCont, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CantMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20)
                        .addComponent(txtNumAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(txtNumAdult, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtNumNinos, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)))
                        .addComponent(jLabel7)
                        .addComponent(jLabel6)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel11)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtPrecioAlquiler)
                        .addComponent(txtDepositoG)
                        .addComponent(txtPorcenIA)
                        .addComponent(txtCedInquilino)
                        .addComponent(txtIDVivi, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1)
                        .addGap(43, 43, 43)
                        .addComponent(jButton2)
                        .addGap(53, 53, 53)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(26, 26, 26)
                        .addComponent(jButton5)
                        .addGap(46, 46, 46)
                        .addComponent(jButton8)
                        .addGap(27, 27, 27)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtPrecioAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtPorcenIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNumAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FechaCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CantMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNumAdult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtNumNinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDepositoG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtCedInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(txtIDVivi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton8)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         posi =  jTable2.getSelectedRow();
        
        Alquileres  Aux = (Alquileres) MenuPrinc.listaAlquileres.get(posi);
        try {
         CantMeses.setText(String.valueOf(Aux.getCantMeses()));
         FechaCont.setText(Aux.getFechContrato());
         txtCedInquilino.setText(String.valueOf(Aux.getCedInquilino()));
         txtDepositoG.setText(String.valueOf(Aux.getDepositoGarantia()));
         txtEstado.setSelectedItem(Aux.getEstado());
         txtIDVivi.setText(String.valueOf(Aux.getIdVvienda()));
         txtNumAdult.setText(String.valueOf(Aux.getNumAdultos()));
         txtNumAlquiler.setText(String.valueOf(Aux.getNumAlquiler()));
         txtNumNinos.setText(String.valueOf(Aux.getNumNinos()));
         txtPorcenIA.setText(String.valueOf(Aux.getPorcincremAnual()));
         txtPrecioAlquiler.setText(String.valueOf(Aux.getPrecioAlquiler()));
        } catch (Exception e) {
              JOptionPane.showMessageDialog(null,"SELECCIONE UNA FILA");
        }


   /**
   * 

    */                


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      Boolean Existencia = false;
     if(!txtBuscar.getText().isEmpty()){
               Alquileres  Aux = null;
              String str = txtBuscar.getText();
          for (int i = 0; i < MenuPrinc.listaAlquileres.size(); i++) {
              Aux = (Alquileres) MenuPrinc.listaAlquileres.get(i);
              if(Integer.toString(Aux.getNumAlquiler()).equals(str)){
                mostrarDatos(Aux); 
                Existencia=true;
           }
            
        }
        
    }else{
        
        JOptionPane.showMessageDialog(null,"La casilla Buscar esta vacia");
    }
   
        
        if(Existencia){
        JOptionPane.showMessageDialog(null,"Busqueda finalizada");
        }else{
         JOptionPane.showMessageDialog(null,"Lo sentimos no se ha encontrado la información en la base de datos :(");    
        }
        
         txtBuscar.setText("");    
        
    }//GEN-LAST:event_jButton6ActionPerformed

    
    public void mostrarDatos(Alquileres Aux) {
       
          String M[][]= new String[1][11];
             M[0][0]=Integer.toString(Aux.getNumAlquiler());
             M[0][1]=Aux.getFechContrato();
             M[0][2]=Integer.toString(Aux.getCantMeses());
             M[0][3]=Integer.toString(Aux.getNumAdultos());
             M[0][4]=Integer.toString(Aux.getNumNinos());
             M[0][5]=Integer.toString(Aux.getDepositoGarantia());
             M[0][6]=Integer.toString(Aux.getPrecioAlquiler());
             M[0][7]=Integer.toString(Aux.getPorcincremAnual());
             M[0][8]=Integer.toString(Aux.getCedInquilino());
             M[0][9]=Integer.toString(Aux.getIdVvienda());
             M[0][10]=Aux.getEstado();
            
             VerPersona(M); // Este metodo muestra los datos buscados, en los textfields
           jTable2.setModel(new javax.swing.table.DefaultTableModel(
            M,
            new String [] {
                "Numero.Alquiler", "Fecha.contrato", "Cant.Meses", "Numero.Adultos", "Numero.niños", "Deposito.G", 
                "Precio.Alquiler", "Porce.I.A", "Cedula.Inquilino", "ID.Vivienda", "Estado"
            }
        ));
        
        
        
    }
    
    
     public void VerPersona(String[][] M) {
         txtNumAlquiler.setText(M[0][0]);
         FechaCont.setText(M[0][1]);
         CantMeses.setText(M[0][2]);
         txtNumAdult.setText(M[0][3]);
         txtNumNinos.setText(M[0][4]);
         txtDepositoG.setText(M[0][5]);
         txtPrecioAlquiler.setText(M[0][6]);
         txtPorcenIA.setText(M[0][7]);
         txtCedInquilino.setText(M[0][8]);
         txtIDVivi.setText(M[0][9]);
         txtEstado.setSelectedItem(M[0][10]);
      
    }
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        MenuPrinc Volv2 = new  MenuPrinc();
         Volv2.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
    if(!CantMeses.getText().isEmpty() &&  !FechaCont.getText().isEmpty() &&  
       !txtCedInquilino.getText().isEmpty() && !txtDepositoG.getText().isEmpty() && 
       txtEstado.getSelectedIndex()>0 &&  !txtIDVivi.getText().isEmpty() &&
       !txtNumAdult.getText().isEmpty() && !txtNumAlquiler.getText().isEmpty() &&
       !txtNumNinos.getText().isEmpty()  && !txtPorcenIA.getText().isEmpty() &&
       !txtPrecioAlquiler.getText().isEmpty() ){
           
           
              //// Este "for" realiza una busqueda para  comprobar si el identicador ingresado Existe 
                 Boolean Existencia1=true;
                 String str = txtNumAlquiler.getText();
                 for (int i = 0; i < MenuPrinc.listaAlquileres.size(); i++) {
                   Alquileres  Aux = (Alquileres) MenuPrinc.listaAlquileres.get(i);
                     if(Integer.toString(Aux.getNumAlquiler()).equals(str)){
                           Existencia1=false;
                      }    
                  }
         
                 
             if(Existencia1){
                 
                Alquileres Persona = new Alquileres(Integer.parseInt(txtNumAlquiler.getText()),FechaCont.getText(),
                Integer.parseInt(CantMeses.getText()),Integer.parseInt(txtNumAdult.getText()),
                Integer.parseInt(txtNumNinos.getText()),Integer.parseInt( txtDepositoG.getText()),
                Integer.parseInt( txtPrecioAlquiler.getText()),Integer.parseInt( txtPorcenIA.getText()),
                Integer.parseInt( txtCedInquilino.getText()),Integer.parseInt( txtIDVivi.getText()), (String) txtEstado.getSelectedItem());
             
                MenuPrinc.listaAlquileres.add(Persona);
                Actualizar();
                Limpiar();
             
             }else{
                    JOptionPane.showMessageDialog(null,"El Identificador : "+txtNumAlquiler.getText()+"  Ya  existe , Por favor ingrese un nuevo valor");
             }
            
            
    }else{
       JOptionPane.showMessageDialog(null,"Hay Una casilla vacia");
                     
     }
       
    }//GEN-LAST:event_jButton1ActionPerformed
   
    
    public void Limpiar(){
       
         CantMeses.setText("");
         FechaCont.setText("");
         txtCedInquilino.setText("");
         txtDepositoG.setText("");
         txtEstado.setSelectedIndex(0);
         txtIDVivi.setText("");
         txtNumAdult.setText("");
         txtNumAlquiler.setText("");
         txtNumNinos.setText("");
         txtPorcenIA.setText("");
         txtPrecioAlquiler.setText("");
          
   }
    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        
       int Fila =    jTable2.getSelectedRow();
       if(Fila>=0){
         MenuPrinc.listaAlquileres.remove(Fila);
          Actualizar();
       }else{
           
           JOptionPane.showMessageDialog(null,"Seleccione La fila que desea eliminar");
       }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed


  String V [] ={"SI","NO"}; 
       
      int N = JOptionPane.showOptionDialog(null,"¿Deseas Eliminar Esta información?","Titulo",0,0,null,V,null);
      if(N==0){
        MenuPrinc.listaAlquileres.removeAll(MenuPrinc.listaAlquileres);
        Actualizar();
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

          Alquileres PersonaModificada = new Alquileres(Integer.parseInt(txtNumAlquiler.getText()),FechaCont.getText(),
             Integer.parseInt(CantMeses.getText()),Integer.parseInt(txtNumAdult.getText()),
             Integer.parseInt(txtNumNinos.getText()),Integer.parseInt( txtDepositoG.getText()),
             Integer.parseInt( txtPrecioAlquiler.getText()),Integer.parseInt( txtPorcenIA.getText()),
             Integer.parseInt( txtCedInquilino.getText()),Integer.parseInt( txtIDVivi.getText()), (String) txtEstado.getSelectedItem());
             
          MenuPrinc.listaAlquileres.set( posi,PersonaModificada);
          Actualizar();
          Limpiar();


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       Actualizar();
       Limpiar();

    }//GEN-LAST:event_jButton8ActionPerformed
    public void  Actualizar(){
          String M[][] = new String[MenuPrinc.listaAlquileres.size()][11];
            
            for (int i = 0; i < MenuPrinc.listaAlquileres.size(); i++) {
            Alquileres  Aux = (Alquileres) MenuPrinc.listaAlquileres.get(i);
           
             M[i][0]=Integer.toString(Aux.getNumAlquiler());
             M[i][1]=Aux.getFechContrato();
             M[i][2]=Integer.toString(Aux.getCantMeses());
             M[i][3]=Integer.toString(Aux.getNumAdultos());
             M[i][4]=Integer.toString(Aux.getNumNinos());
             M[i][5]=Integer.toString(Aux.getDepositoGarantia());
             M[i][6]=Integer.toString(Aux.getPrecioAlquiler());
             M[i][7]=Integer.toString(Aux.getPorcincremAnual());
             M[i][8]=Integer.toString(Aux.getCedInquilino());
             M[i][9]=Integer.toString(Aux.getIdVvienda());
             M[i][10]=Aux.getEstado();
            }
              
          jTable2.setModel(new javax.swing.table.DefaultTableModel(
            M,
            new String [] {
                "Numero.Alquiler", "Fecha.contrato", "Cant.Meses", "Numero.Adultos", "Numero.niños", "Deposito.G", 
                "Precio.Alquiler", "Porce.I.A", "Cedula.Inquilino", "ID.Vivienda", "Estado"
            }
        ));
       
       
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fromAlquileres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fromAlquileres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fromAlquileres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fromAlquileres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fromAlquileres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CantMeses;
    private javax.swing.JTextField FechaCont;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCedInquilino;
    private javax.swing.JTextField txtDepositoG;
    private javax.swing.JComboBox<String> txtEstado;
    private javax.swing.JTextField txtIDVivi;
    private javax.swing.JTextField txtNumAdult;
    private javax.swing.JTextField txtNumAlquiler;
    private javax.swing.JTextField txtNumNinos;
    private javax.swing.JTextField txtPorcenIA;
    private javax.swing.JTextField txtPrecioAlquiler;
    // End of variables declaration//GEN-END:variables

   

}
