/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallaprinc;

import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class fromInquilinos extends javax.swing.JFrame {
    int posi;
    /**
     * Creates new form fromInquilinos
     */
    public fromInquilinos() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtGenero = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFechaNacimiento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEmial = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtOcupacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Insertar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        EliminarTodo = new javax.swing.JButton();
        Seleccionar = new javax.swing.JButton();
        GuardarModificacion = new javax.swing.JButton();
        BnBuscar = new javax.swing.JButton();
        VolverMenuPrinciapal = new javax.swing.JButton();
        Mostrar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cedula");

        jLabel2.setText("Nombre");

        txtGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir", "Femenino", "Masculino" }));

        jLabel3.setText("Genero");

        jLabel4.setText("Fecha Nacimiento");

        jLabel5.setText("Dirección");

        jLabel6.setText("Telélfono");

        jLabel7.setText("Email");

        jLabel8.setText("Ocupación");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre", "Genero", "Email", "Fecha.N", "Dirección", "Teléfono", "Ocupación"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Insertar.setText("Insertar");
        Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        EliminarTodo.setText("Eliminar todo");
        EliminarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarTodoActionPerformed(evt);
            }
        });

        Seleccionar.setText("Seleccionar");
        Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarActionPerformed(evt);
            }
        });

        GuardarModificacion.setText("Guardar Modificación");
        GuardarModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarModificacionActionPerformed(evt);
            }
        });

        BnBuscar.setText("Buscar");
        BnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnBuscarActionPerformed(evt);
            }
        });

        VolverMenuPrinciapal.setText("Volver a menu principal");
        VolverMenuPrinciapal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverMenuPrinciapalActionPerformed(evt);
            }
        });

        Mostrar.setText("Mostrar");
        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Insertar)
                        .addGap(18, 18, 18)
                        .addComponent(Eliminar)
                        .addGap(30, 30, 30)
                        .addComponent(EliminarTodo)
                        .addGap(33, 33, 33)
                        .addComponent(Seleccionar)
                        .addGap(30, 30, 30)
                        .addComponent(GuardarModificacion)
                        .addGap(29, 29, 29)
                        .addComponent(Mostrar)
                        .addGap(18, 18, 18)
                        .addComponent(BnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 96, Short.MAX_VALUE))
                            .addComponent(txtEmial)
                            .addComponent(txtNombre)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(txtDireccion)
                    .addComponent(txtTelefono)
                    .addComponent(txtOcupacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VolverMenuPrinciapal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VolverMenuPrinciapal))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEmial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Insertar)
                    .addComponent(Eliminar)
                    .addComponent(EliminarTodo)
                    .addComponent(Seleccionar)
                    .addComponent(GuardarModificacion)
                    .addComponent(BnBuscar)
                    .addComponent(Mostrar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarTodoActionPerformed
     String V [] ={"SI","NO"}; 
       
      int N = JOptionPane.showOptionDialog(null,"¿Deseas Eliminar Esta información?","Titulo",0,0,null,V,null);
      if(N==0){
        MenuPrinc.listaInquilinos.removeAll(MenuPrinc.listaInquilinos);
        Actualizar();
      }
        
        
    }//GEN-LAST:event_EliminarTodoActionPerformed

    private void VolverMenuPrinciapalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverMenuPrinciapalActionPerformed

       MenuPrinc Volv3 = new  MenuPrinc();
         Volv3.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_VolverMenuPrinciapalActionPerformed

    private void InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarActionPerformed
     
        
       if(!txtcedula.getText().isEmpty() && !txtNombre.getText().isEmpty() && txtGenero.getSelectedIndex()>0 &&
               !txtFechaNacimiento.getText().isEmpty() && !txtDireccion.getText().isEmpty() && !txtTelefono.getText().isEmpty() 
               && !txtEmial.getText().isEmpty() && !txtOcupacion.getText().isEmpty()){ 
        
           
                 Boolean Existencia1=true;
                 String str = txtcedula.getText();
                 for (int i = 0; i < MenuPrinc.listaInquilinos.size(); i++) {
                      Inquilinos Aux =  (Inquilinos) MenuPrinc.listaInquilinos.get(i);
                     if(Integer.toString(Aux.getCedInqui()).equals(str)){
                           Existencia1=false;
                      }    
                  }
      
           
             if(Existencia1){
                    Inquilinos  persona = new Inquilinos(Integer.parseInt(txtcedula.getText()),txtNombre.getText(),
                   (String) txtGenero.getSelectedItem(),txtFechaNacimiento.getText(),txtDireccion.getText(),
                   txtTelefono.getText(), txtEmial.getText(),txtOcupacion.getText());
              
                   MenuPrinc.listaInquilinos.add(persona);
                   Actualizar();
                   Limpiar();
             }else{
               
               JOptionPane.showMessageDialog(null,"El Identificador :"+txtcedula.getText()+" Ya  existe , Por favor ingrese un nuevo valor");
            } 
            
            
            
       }else{ 
           
             JOptionPane.showMessageDialog(null,"Hay Una casilla vacia");
       }
    

    }//GEN-LAST:event_InsertarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed

        int Fila = jTable1.getSelectedRow();
       if(Fila>=0){
          MenuPrinc.listaInquilinos.remove(Fila);
          Actualizar();
       }else{
           
           JOptionPane.showMessageDialog(null,"Seleccione La fila que desea eliminar");
       }




        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarActionPerformed

    private void SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarActionPerformed

      posi =jTable1.getSelectedRow();
      Inquilinos Aux =  (Inquilinos) MenuPrinc.listaInquilinos.get(posi);
       try {
      txtcedula.setText(Integer.toString(Aux.getCedInqui()));
      txtNombre.setText(Aux.getNomInqui());
      txtGenero.setSelectedItem(Aux.getGenero());
      txtFechaNacimiento.setText(Aux.getFechNac()); 
      txtDireccion.setText(Aux.getText());  
      txtTelefono.setText(Aux.getTelefono()); 
      txtEmial .setText(Aux.getEmail()); 
      txtOcupacion.setText(Aux.getOcupacion()); 
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Seleccione La fila que desea eliminar");
        }





        // TODO add your handling code here:
    }//GEN-LAST:event_SeleccionarActionPerformed

    private void GuardarModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarModificacionActionPerformed

     Inquilinos  personaModificada = new Inquilinos(Integer.parseInt(txtcedula.getText()),txtNombre.getText(),
                   (String) txtGenero.getSelectedItem(),txtFechaNacimiento.getText(),txtDireccion.getText(),
                   txtTelefono.getText(), txtEmial.getText(),txtOcupacion.getText());
         MenuPrinc.listaInquilinos.set(posi, personaModificada);
         Limpiar();
         Actualizar();


        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarModificacionActionPerformed

    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed

     Limpiar();
     Actualizar();
       
    }//GEN-LAST:event_MostrarActionPerformed

    private void BnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnBuscarActionPerformed

       Boolean Existencia = false;
     if(!txtBuscar.getText().isEmpty()){
               Inquilinos Aux = null;
              String str = txtBuscar.getText();
          for (int i = 0; i < MenuPrinc.listaInquilinos.size(); i++) {
              Aux = (Inquilinos) MenuPrinc.listaInquilinos.get(i);
              if(Integer.toString(Aux.getCedInqui()).equals(str)){
                mostrarDatos(Aux); 
                Existencia=true;
           }   
        }
        
    }else{
        
        JOptionPane.showMessageDialog(null,"La casilla Buscar esta vacia");
    }
   
     
     
     
        //Resultados de la Busqueda
        if(Existencia){
        JOptionPane.showMessageDialog(null,"Busqueda finalizada");
        }else{
         JOptionPane.showMessageDialog(null,"Lo sentimos no se ha encontrado la información en la base de datos :(");    
        }
        
         txtBuscar.setText("");

    }//GEN-LAST:event_BnBuscarActionPerformed
   
    public  void mostrarDatos(Inquilinos Aux) {
      
         String M[][] = new String[1][8];
            
             
             M[0][0]= Integer.toString(Aux.getCedInqui());
             M[0][1]=Aux.getNomInqui();
             M[0][2]=Aux.getGenero();
             M[0][3]=Aux.getEmail();
             M[0][4]=Aux.getFechNac();
             M[0][5]=Aux.getText();
             M[0][6]=Aux.getTelefono();
             M[0][7]= Aux.getOcupacion();
             
            VerPersona(M); // Este metodo muestra los datos buscados, en los textfields
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            M,
            new String [] {
                "Cédula", "Nombre", "Genero", "Email", "Fecha.N", "Dirección", "Teléfono", "Ocupación"
            }
        ));
        
    }
    
    
     public  void VerPersona(String[][] M) {
         
      txtcedula.setText(M[0][0]);
      txtNombre.setText(M[0][1]);
      txtGenero.setSelectedItem(M[0][2]);
      txtEmial .setText(M[0][3]); 
      txtFechaNacimiento.setText( M[0][4]); 
      txtDireccion.setText( M[0][5]);  
      txtTelefono.setText(M[0][6]);
      txtOcupacion.setText(M[0][7]);  
    }
     
     
    public void Limpiar(){
        
      txtcedula.setText("");
      txtNombre.setText("");
      txtGenero.setSelectedIndex(0);
      txtFechaNacimiento.setText(""); 
      txtDireccion.setText("");  
      txtTelefono.setText(""); 
      txtEmial .setText(""); 
      txtOcupacion.setText("");
        
    }
    
     public void Actualizar(){
         
         String M[][] = new String[MenuPrinc.listaInquilinos.size()][8];
            
            for (int i = 0; i < MenuPrinc.listaInquilinos.size(); i++) {
             Inquilinos Aux =  (Inquilinos) MenuPrinc.listaInquilinos.get(i);
             
             M[i][0]= Integer.toString(Aux.getCedInqui());
             M[i][1]=Aux.getNomInqui();
             M[i][2]=Aux.getGenero();
             M[i][3]=Aux.getEmail();
             M[i][4]=Aux.getFechNac();
             M[i][5]=Aux.getText();
             M[i][6]=Aux.getTelefono();
             M[i][7]= Aux.getOcupacion();
            }
         
         jTable1.setModel(new javax.swing.table.DefaultTableModel(
            M,
            new String [] {
                "Cédula", "Nombre", "Genero", "Email", "Fecha.N", "Dirección", "Teléfono", "Ocupación"
            }
        ));
         
         
         
         
     }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fromInquilinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fromInquilinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fromInquilinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fromInquilinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fromInquilinos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BnBuscar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton EliminarTodo;
    private javax.swing.JButton GuardarModificacion;
    private javax.swing.JButton Insertar;
    private javax.swing.JButton Mostrar;
    private javax.swing.JButton Seleccionar;
    private javax.swing.JButton VolverMenuPrinciapal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmial;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JComboBox<String> txtGenero;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtOcupacion;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtcedula;
    // End of variables declaration//GEN-END:variables

   

    
}
